=== pontch/WBA2/wba2-2/bin/module.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="module">	
		<xs:complexType>	
			<xs:sequence>
				<xs:element name="modul" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titel">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="kategorie" type="xs:string" />
											<xs:attribute name="id" type="xs:integer" />
											<xs:attribute name="kuerzel" type="xs:string" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="status" type="xs:string"/>
							<xs:element name="credits" type="xs:string"/>
							<xs:element name="aufwand" type="xs:string"/>
							<xs:element name="termin" type="xs:string"/>
							<xs:element name="beschreibung">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="thema" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="text" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
															 <xs:extension base="xs:string">
															 	<xs:attribute name="titel" type="xs:string" />
															 </xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
													<xs:element name="aufzaehlung" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="punkt" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="newsticker">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="eintrag" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute name="datum" type="xs:date"/>
														<xs:attribute name="verfasser" type="xs:string"/>
														<xs:attribute name="modul" type="xs:string"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="titel" type="xs:string" />
								</xs:complexType>
							</xs:element>
							<xs:element name="abonnenten">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="abonnent" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="name" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== pontch/WBA2/wba2-2/src/modulWBA2.xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="module.xsd">
	<modul>
		<titel kategorie="modul" id="1" kuerzel="WBA2">Web-basierte Anwendungen 2: Verteilte Systeme</titel>
		<status>Pflichtfach</status>
		<credits>5 ECTS-P</credits>
		<aufwand>4 SWS</aufwand>
		<termin>jährlich angeboten</termin>
		
		<beschreibung>
			<thema>
				<text titel="Dozent">Prof. Dr. Kristian Fischer </text>
			</thema>
			<thema>
				<text titel="Ziele">Die Studierenden sollen in der Lage sein, alternative Architekturen für Informationssysteme 
				im Web zu identifizieren, deren Eigenschaften zu benennen und sie gegeneinander abzugrenzen.
				Dazu sollen die Studierenden im Einzelnen:</text>
				<aufzaehlung>
					<punkt>* auf der Basis der Kenntnis wesentlicher klassischer Middelewaresysteme die grundlegenden Web Services Protokolle 
					benennen, einordnen und diskutieren können,</punkt>
					<punkt>* eine geeignete Vorgehensweise zum Entwurf eines dienstorientierten Informationssystems im Web wählen können,</punkt>
					<punkt>* die praktischen Herausforderungen einer Umsetzung anhand eines eigenen Miniprojekts meistern können,</punkt>
					<punkt>* die Bedeutung der Modellierung von Daten in offenen Umgebungen benennen können und die Eigenschaften der 
					Datenmodellierung in XML bzw. in RDF diskutieren können,</punkt>
					<punkt>* die relevanten Standards und Architekturen für stream-orientierte interpersonale Kommunikation im Web kennen und 
					abgrenzen können.</punkt>
				</aufzaehlung>
			</thema>
			<thema>
				<text titel="Lehrinhalte" />
				<aufzaehlung>
					<punkt>Modellierung von Daten für die Kommunikation im Web: Datenkommunikation in offenen Umgebungen; Prinzip von 
					Auszeichnungssprachen; Datenmodellierung mit XML und XML Schemasprachen; Datenmodellierung mit RDF und RDFS </punkt>
					<punkt>Infrastruktur und Standards: klassische Middlewaresysteme: RPC,CORBA, nachrichtenorientierte Middleware; Standards 
					und Standardisierung im Internet; quelloffene vs. proprietäre Software</punkt>
					<punkt>Dienstorientierte Architektur: Basisstandards: SOAP, WSDL, UDDI; Dienstkomposition; Transaktionen; Entwurfsprinzipen: 
					top-down vs. bottom-up, Kohäsion, Granularität</punkt>
					<punkt>Kommunikationsarchitekturen: Streaming Protokolle: RTP, RSVP, RTCP; Dienstgüte; Signalisierungsprotokolle: SIP, H.323; 
					Präsenzarchitekturen</punkt>
				</aufzaehlung>
			</thema>
			<thema>
				<text titel="Lehrmethode">Vorlesung, Übung </text>
			</thema>
			<thema>
				<text titel="Vorraussetzungen">Datenbanken, Softwaretechnik I, Grundlagen von Multimedia Systemen, Grundkenntnisse der 
				objektorientierten Programmierung, Grundkenntnisse der Kommunikationstechnik, Netzbasierte Anwendungen </text>
			</thema>
			<thema>
				<text titel="Veranstaltungsort">Raum 3101</text>
			</thema>
		</beschreibung>
		<newsticker titel="Newsticker">
			<eintrag datum="2013-05-06" verfasser="Prof. Dr. Kristian Fischer" modul="WBA2">Vorlesung fällt aus!</eintrag>
			<eintrag datum="2013-04-23" verfasser="Prof. Dr. Kristian Fischer" modul="WBA2">Bis zum 26.04.2013 müssen die Aufgaben der 1. Phase hochgeladen werden.</eintrag>
			<eintrag datum="2013-04-10" verfasser="Prof. Dr. Kristian Fischer" modul="WBA2">Der nächste Praktikumstermin ist keine Pflicht, sondern dient nur der Beratung! Dazu können 
			Termine bei den Tutoren vereinbart werden.</eintrag>
			<eintrag datum="2013-03-14" verfasser="Prof. Dr. Kristian Fischer" modul="WBA2">WBA2 startet am 15.05.2013! Oraganisatorische Sachen werden in der ersten Vorlesung besprochen.</eintrag>
		</newsticker>
		<abonnenten>
			<abonnent name="Daniela Kucharczyk" />
		</abonnenten>
	</modul>
</module>
