=== pontch/WBA2/wba2-2/bin/semester.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mi_semester">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="semester">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="zeitpunkt">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="kuerzel" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="modulplan">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="modul" minOccurs="0" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="titel" type="xs:string" />
													<xs:element name="dozent" type="xs:string" />
												</xs:sequence>
												<xs:attribute name="credits" type="xs:string"/>
												<xs:attribute name="aufwand" type="xs:string" />
												<xs:attribute name="termin" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== pontch/WBA2/wba2-2/src/semester4.xml
<?xml version="1.0" encoding="UTF-8"?>
	<mi_semester xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="semester.xsd">
		<semester>
			<zeitpunkt kuerzel="SS">Studiensemester 4</zeitpunkt>
			<modulplan>
				<modul credits="5 ECTS-P" aufwand="4 SWS" termin="jährlich angeboten">
					<titel>Betriebssysteme und verteilte Systeme</titel>
					<dozent>Prof. Dr. Horst Stenzel</dozent>
				</modul>
				<modul credits="5 ECTS-P" aufwand="4 SWS" termin="jährlich angeboten">
					<titel>Mensch-Computer Interaktion</titel>
					<dozent>Prof. Dr. Gerhard Hartmann</dozent>
				</modul>
				<modul credits="5 ECTS-P" aufwand="4 SWS" termin="jährlich angeboten">
					<titel>Softwaretechnik</titel>
					<dozent>Prof. Dr. Mario Winter</dozent>
				</modul>
				<modul credits="5 ECTS-P" aufwand="4 SWS" termin="jährlich angeboten">
					<titel>Web-basierte Anwendungen 2: Verteilte Systeme</titel>
					<dozent>Prof. Dr. Kristian Fischer</dozent>
				</modul>
				<modul credits="5 ECTS-P" aufwand="4 SWS" termin="jährlich angeboten">
					<titel>WPF Veranstaltung I</titel>
					<dozent>Alle Professorinnen und Professoren des Instituts für Informatik</dozent>
				</modul>
				<modul credits="5 ECTS-P" aufwand="4 SWS" termin="jährlich angeboten">
					<titel>Grundlagen BWL </titel>
					<dozent>Prof. Dr. Matina Behr</dozent>
				</modul>
			</modulplan>
		</semester>
	</mi_semester>
